package tui

var uiMessages = map[string][2]string{
	"status.loading":    {"Loading…", "正在加载…"},
	"status.canceled":   {"Canceled", "已取消"},
	"status.partial":    {"Partially failed", "部分失败"},
	"set.apply":         {"Apply", "应用"},
	"set.cancel":        {"Cancel", "取消"},
	"set.buttons.help":  {"Apply saves and stays here; Cancel discards the draft and returns.", "应用后留在本页；取消丢弃未保存修改并返回。"},
	"set.positive":      {"Enter a positive integer.", "请输入正整数。"},
	"set.proxy.invalid": {"Use protocol://host:port.", "请使用 协议://主机:端口。"},
	"run.details":       {"Details", "详情"},
	"run.stop":          {"Stop", "停止"},
	"run.collapsed":     {"Details collapsed · press d to expand", "详情已折叠 · 按 d 展开"},
}

var fieldHelp = map[string][2]string{
	"Login type":                     {"Choose QR (default), code, or Desktop session import.", "选择默认二维码、验证码或桌面客户端会话导入。"},
	"Desktop path":                   {"Telegram Desktop data directory, used for Desktop import.", "导入桌面客户端会话时填写 Telegram Desktop 数据目录。"},
	"Passcode":                       {"Local Telegram Desktop passcode, if one is configured.", "桌面客户端的本地密码；未设置则留空。"},
	"Message URLs (comma separated)": {"Telegram message links separated by commas.", "填写 Telegram 消息链接，多条用逗号分隔。"},
	"Export files (comma separated)": {"Message export JSON paths, separated by commas.", "填写消息导出 JSON 文件路径，多个用逗号分隔。"},
	"Output dir":                     {"Download directory; missing directories are created.", "下载保存目录；目录不存在时自动创建。"},
	"Include ext":                    {"Only these extensions, e.g. mp4,mp3; cannot combine with exclude.", "只包含这些扩展名，例如 mp4,mp3；不能与排除同时使用。"},
	"Exclude ext":                    {"Exclude these extensions, e.g. png,jpg; cannot combine with include.", "排除这些扩展名，例如 png,jpg；不能与包含同时使用。"},
	"Rewrite ext":                    {"Determine the extension from the downloaded file contents.", "下载后依据实际文件内容修正扩展名。"},
	"Skip same name":                 {"Skip files with matching name (without extension) and size.", "跳过文件名（不含扩展名）及大小相同的文件。"},
	"Newest first":                   {"Process newer messages first.", "优先处理较新的消息。"},
	"Grouped media":                  {"Include other media in the same album.", "自动包含同一媒体组中的其他文件。"},
	"Takeout session":                {"Use Telegram export sessions; Telegram may require a waiting period.", "使用 Telegram 导出会话；服务端可能要求等待。"},
	"Serve over HTTP":                {"Serve media over local HTTP instead of saving it.", "通过本地 HTTP 提供媒体，不直接下载保存。"},
	"Paths (comma separated)":        {"Files or directories to upload; directories are traversed recursively.", "上传文件或目录路径；目录递归展开，多个路径用逗号分隔。"},
	"Chat":                           {"Chat ID or username; leave empty for Saved Messages where supported.", "填写会话 ID 或用户名；支持的操作中留空表示收藏夹。"},
	"Topic id":                       {"Forum topic ID; leave empty for the default topic.", "论坛主题 ID；留空使用默认主题。"},
	"To (router expr)":               {"Destination or routing expression; use Chat for a simple target.", "目标或路由表达式；普通目标可以直接填写会话字段。"},
	"Remove after upload":            {"Delete the source only after successful upload; use with care.", "上传成功后删除本地源文件，请确认后使用。"},
	"As photo":                       {"Send supported images as photos instead of documents.", "将支持的图片作为照片发送，而非文件。"},
	"Disable auto thumbnail":         {"Skip automatic ffmpeg thumbnail generation; an existing .thumb sidecar is still used.", "不使用 ffmpeg 自动生成视频封面；已有的 .thumb 封面仍会使用。"},
	"Output":                         {"Output format; empty uses the command default.", "输出格式；未选择时使用命令默认值。"},
	"Filter expr":                    {"Filter expression; true matches all items.", "过滤表达式；true 表示匹配全部项目。"},
	"Export type":                    {"Select an ID range, time range, or the most recent messages.", "选择按消息 ID、时间范围或最近消息导出。"},
	"Input (comma separated)":        {"Arguments for the selected export type, separated by commas.", "当前导出类型需要的范围或数量，多个值用逗号分隔。"},
	"Output file":                    {"Path for the exported results file.", "导出结果文件的保存路径。"},
	"With content":                   {"Include message text in the export.", "导出时包含消息正文。"},
	"All messages":                   {"Include all messages, not only media messages.", "包含所有消息，而不仅是媒体消息。"},
	"Raw struct":                     {"Export raw Telegram structures for advanced processing.", "导出 Telegram 原始结构，供进一步处理。"},
	"Chat domain":                    {"Channel username or domain to query.", "要查询的频道用户名或域名。"},
	"From (comma separated)":         {"Source message links or export files, separated by commas.", "来源消息链接或导出文件，多个用逗号分隔。"},
	"To":                             {"Destination chat or routing expression.", "目标会话或路由表达式。"},
	"Edit expr":                      {"Expression to edit forwarded messages; empty leaves them unchanged.", "编辑转发消息的表达式；留空保持原内容。"},
	"Mode":                           {"Copy sends a new message; Forward preserves forwarding attribution.", "复制模式发送新消息；转发模式保留转发来源。"},
	"Silent":                         {"Send without notifying the destination.", "静默发送，不通知目标会话。"},
	"Dry run":                        {"Preview the operation without performing its changes.", "预览操作，不执行实际更改。"},
	"No grouped detect":              {"Treat each message independently, without album detection.", "逐条处理消息，不自动检测媒体组。"},
	"Reverse order":                  {"Process the selected messages in reverse order.", "按相反顺序处理选中的消息。"},
	"Destination":                    {"Backup destination path; empty uses the command default.", "备份目标路径；留空使用命令默认值。"},
	"Backup file":                    {"Existing backup file to restore.", "要恢复的现有备份文件路径。"},
	"No confirmation":                {"Skip the update confirmation prompt.", "跳过更新确认提示。"},
	"Target version":                 {"Version to install, e.g. v0.20.4; empty chooses the latest.", "要安装的版本，例如 v0.20.4；留空选择最新版本。"},
	"Force reinstall":                {"Reinstall even when the selected version is already installed.", "即使已安装目标版本，也重新安装。"},
	"form.extra":                     {"Additional simple CLI arguments, e.g. --continue.", "附加命令参数，例如 --continue；请使用命令行参数格式。"},
	"set.language":                   {"Language for subsequent screens and commands.", "后续界面使用的语言。"},
	"set.ns":                         {"Account namespace for subsequent commands; empty means default.", "后续命令使用的账号命名空间；留空表示 default。"},
	"set.proxy":                      {"Proxy URL; empty uses no explicit proxy.", "代理地址；留空表示不指定代理。"},
	"set.threads":                    {"Positive number of transfer threads per file; empty uses the default.", "每个文件的传输线程数，填写正整数；留空使用默认值。"},
	"set.limit":                      {"Positive number of concurrent files; empty uses the default.", "同时处理的文件数，填写正整数；留空使用默认值。"},
}
